# Generated by Django 3.1.6 on 2021-03-07 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.CharField(default='', max_length=300),
        ),
    ]
